<?php if ($this->filter) : ?>
  <div class="row">
    <?php foreach ($this->filter as $filter) : ?>

      <div class="col-xs-12 col-sm-<?php echo 12 / count($this->filter); ?>">

        <?php if ($filter['type'] == 'search') : ?>
          <?php echo $this->partial('table/partial/filter/search', ['filter' => $filter]); ?>

        <?php elseif ($filter['type'] == 'language') : ?>
          <?php echo $this->partial('table/partial/filter/language', ['filter' => $filter]); ?>

        <?php elseif ($filter['type'] == 'model') : ?>
          <?php echo $this->partial('table/partial/filter/model', ['filter' => $filter]); ?>

        <?php elseif ($filter['type'] == 'datetime') : ?>
          <?php echo $this->partial('table/partial/filter/datetime', ['filter' => $filter]); ?>

        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
