<?php /** @var \Light\Form\Element\Image $element */ ?>
<?php $element = $this->element; ?>

<div data-element-imagesingle="true"
     class="imagesingle-container container-fluid"
     data-storage-url="/<?php echo \Light\Front::getInstance()->getConfig()['light']['storage']['route']; ?>/frame"
     data-name="<?php echo $element->getName(); ?>">
  <a data-select="true" class="btn btn-primary bmd-ripple bmd-fab bmd-fab-sm bmd-floating">
    <span class="bmd-icon flaticon-add182"></span>
  </a>
  <input name="<?php echo $element->getName(); ?>" value="<?php echo $element->getValue(); ?>" type="hidden"/>
  <div data-image-container="true">
    <?php if ($value = $element->getValue()) : ?>
      <?php $ext = explode('.', $value)[count(explode('.', $value)) - 1]; ?>

      <?php if ($ext == 'pdf') : ?>
        <a class="btn btn-default preview-pdf-single bmd-floating bmd-ripple"
           data-pdf-large="<?php echo $value; ?>">
          Открыть документ
        </a>

      <?php elseif (in_array($ext, ['jpg', 'png', 'jpeg'])) :  ?>
        <a class="btn btn-default background-image preview-image-single bmd-floating bmd-ripple" style="background-image: url('<?php echo $value; ?>');"
           data-image-large="<?php echo $value; ?>"></a>

      <?php else: ?>
        <a class="btn btn-default download-file bmd-floating bmd-ripple" target="_blank" href="<?php echo $value; ?>">Открыть файл</a>

      <?php endif; ?>
    <?php endif; ?>
  </div>
  <script type="text/html" data-template-image="true">
    <a class="btn btn-default background-image preview-image-single bmd-floating bmd-ripple" style="background-image: url('{{value}}');"
       data-image-large="{{value}}"></a>
  </script>
  <script type="text/html" data-template-pdf="true">
    <a class="btn btn-default preview-pdf-single bmd-floating bmd-ripple" data-pdf-large="{{value}}">Открыть документ</a>
  </script>
  <script type="text/html" data-template-file="true">
    <a class="btn btn-default download-file bmd-floating bmd-ripple" target="_blank" href="{{value}}">Открыть файл</a>
  </script>
</div>
