<div class="form-group">
  <div class="input-group">
    <span class="input-group-addon bmd-addon">
      <i class="fa fa-search"></i>
    </span>
    <div class="bmd-field-group">
      <input name="filter[search]"
             type="text"
             class="bmd-input"
             value="<?php echo $this->filter['value']; ?>"/>
      <span class="bmd-bar"></span>
      <label class="bmd-label <?php if (!strlen($this->filter['value'])) : ?>down<?php endif; ?>">Поиск...</label>
    </div>
  </div>
</div>

<script>
  window.addEventListener("keydown", e => {
    if (e.keyCode === 114 || (e.ctrlKey && e.keyCode === 70)) {
      e.preventDefault();
      $('[name="filter[search]"]')
        .focus()
        .select();
    }
  });

  $('[name="filter[search]"]').on('keydown', e => {
    if (e.keyCode === 13) {
      $('[data-form-table]').submit();
    }
  });
</script>